### ISSUE TITLE
Register functions with GDScript friendly names

### ISSUE THREAD

**Issue by chippmann** [utopia-rise/godot-kotlin#141]
@2shady4u described the need of defining GDScript friendly method names while registering classes here: https://github.com/utopia-rise/godot-kotlin/issues/66

This is a good idea as sometimes you want to register a method with godot and access it through kotlin as well. With the current solution, you either declare your function name kotlin style camelCase or GDScript style snake_case. But in one of the two languages you end up calling a function which is not written in the correct casing.

If we provide something like this:
```kotlin
@RegisterFunction(rpcMode = RPCMode.None, registeredName = "my_cool_function")
fun myCoolFunction(){}
```
one can call it from kotlin with `myCoolFunction` and from GDScript with `my_cool_function`. 

This would lead to the following limitation though: when using `someNode.callDeferred("")` one would have to write the name from GDScript like this: `someNode.callDeferred("my_cool_function")` and could not use `someNode.callDeferred(SomeNode::myCoolFunction.name)`. But i guess when we say that in the docs it should be fine. Or we could provide extension functions which map the `name`to the correct casing.

Of course this should be completely optional as it would only be used if users mix languages heavily.

Once we are about to implement it, we should discuss the implementation details first.

**Comment by chippmann** [comment]
I suggest that we advise the user to use 
```kotlin
/** Convert a CamelCase string to a snake_case one */
fun String.camelcaseToUnderscoreLowercased(other: String) = asGDString {
    nullSafe(Godot.gdnative.godot_string_camelcase_to_underscore_lowercased)(it.ptr).toKString()
}
```
with this functionality

**Comment by CedNaru** [comment]
This function name is way too long but such as simple task.
I can propose something like this;

- Creating an inline class Callable ( would have the side effect of doing some groundwork for the future Godot new Callable type in 4.0). 
- This inline class would wrap any kind of Kotlin function and would have a method `toGodotName()` using  `camelcaseToUnderscoreLowercased`
-Add in the NativePublic directory an extension for Object callDeferred(Callable). It would just do this:
`this.callDeferred(callable.toGodotName())`
-Do the same for all the methods using a String as a function name.

Instead of 
`someNode.callDeferred(SomeNode::myCoolFunction.name.camelcaseToUnderscoreLowercased())`
we would write
`someNode.callDeferred(Callable(SomeNode::myCoolFunction))`

Of course, both would be possible but I would make the second case the recommended one.

**Comment by piiertho** [comment]
Instantiating a Callable seems overkill to me. I mean syntax is easier, but is it worth to create an instance ?

**Comment by CedNaru** [comment]
It would be an inline class so there is no allocation happening.

**Comment by piiertho** [comment]
Oh ok ! Did not paid attention you were speaking of inline class. Seems good so.

**Comment by chippmann** [comment]
@CedNaru I like this idea. But with it i guess I'll change the annotation to accept a boolean rather than a string. The boolean indicating if the function should be registered as is or with GDScript friendly name.
So something like `@RegisterFunction(registerSnakeCase = true)`. The default being false.
One point remains open though: Looking at your argument for Godot 4.0; The callable should also take in a boolean as an argument wether snake case should be used as function name or not. Otherwise this whole solution would not be optional, It would make it the default. Which i don't particularly like.
Also i would only allow one option. WDYT?

**Comment by raniejade** [comment]
I'm personally not a fan of changing the case of a method depending where it is called. Not only `callDeferred` is affected but also `signals.connect`. This will also introduce a mental overhead for users calling kotlin methods from languages other than GDScript, they have to consider how the method is registered instead of just looking at the name of the method. I think it just adds complexity to the binding with very little benefit (or arguably none at all).

**Comment by CedNaru** [comment]
Quick summary:
-Everything in Godot (even the C++ itself) is using snake_case.
-We are in Kotlin and want to enforce the use of CamelCase (and we did that with all the generated functions, the core functions, and public functions).

4 possibilities and the issues they cause:

- **Writing everything in snake_case in Kotlin**. We would need to rename all the functions we created so far and we would break Kotlin conventions.
- **Writing everything in CamelCase and registering as it is**. Break Godot conventions and sharing Kotlin scripts with other people will be weird because they will be the ones having to suddenly write CamelCase in GDscript. There is also the case where you want to override Godot functions and have no choice but to use snake_case in the middle of your code. 
I also consider calling kotlin script from another language than GdScript to be a really corner case. It's possible of course but really a bother to use (also NativeScript is about performance and calling native functions from another language like this is everything except performant)
- **Naming and registering your functions whatever you want**. A mess to use because people might be confused about what name should be used in functions requiring a string containing a name.
- **Write in CamelCase only, register everything in snake_case**". We don't let a choice to the user and everything is registered with snake_case regardless of their will.

Choice 4 might be too forceful but that's actually the idea I support the most. This way you can follow Godot and Kotlin conventions at the same time, and all uses of strings containing name of functions will be in snake_case as well.

**Comment by CedNaru** [comment]
Example of the issue we would have with the current implementation.
Let's say we have an Engine Object of Class A. And want to create a Kotlin Script B extending A.
A only has one **foo_bar()** method we want to override.

The generated Kotlin version of A does have a method called **fooBar**(), if we try to override and register it, it won't work because that would just create on the Godot side a new function **fooBar** unrelated to **foo_bar**.

Now let's introduce some polymorphism. In this situation, if I try to create an array of A ( that might be instance of B), and want to iterate that array in GdScript in order to call foo_bar on each of them. It's going to call the original A.**foo_bar** even if we got a B ( because the actual method is **fooBar()** ). 

The same situation can also happen the other way around. Let's say that we did register in Kotlin, the function as "**foo_bar**" to stick with the original name and avoid the overriding issue. If this time, I want an array of A inside Kotlin. I can only call **fooBar()** on it, so I won't be able to use the new method in Kotlin as well. 

In both situation we end up with a new class B that have a CamelCase and a snake_version of the same method, one being inherited from the parent, one being the "overridden" version.

**Comment by piiertho** [comment]
I agree with @CedNaru 
Even with cpp bindings, the best practice is to register in snake case. I prefer the 4th option, as it force respect of both conventions 
EDIT : methods like `_physics_process` would be broken.

**Comment by raniejade** [comment]
> Write in CamelCase only, register everything in snake_case". We don't let a choice to the user and everything is registered with snake_case regardless of their will.

I'm okay with this, I just don't like allowing users to configure the case used. Convention over configuration please.

**Comment by piiertho** [comment]
> > Write in CamelCase only, register everything in snake_case". We don't let a choice to the user and everything is registered with snake_case regardless of their will.
> 
> I'm okay with this, I just don't like allowing users to configure the case used. Convention over configuration please.

Completely agree
