### ISSUE TITLE
Some problems following Getting Started

### ISSUE THREAD

**Issue by nanodeath** [utopia-rise/godot-kotlin#145]
Hi there! First of all, excited to try out anything that lets me do gamedev in Kotlin 😄 

However, I ran into a number of hitches in the getting started:

If you navigate directly to Getting Started from the README, it shows documentation for a prerelease version, which is a bit confusing. You *can* click on the link under the "Release README" heading, but it didn't occur to me to do that.

The documented build.gradle.kts includes this bit:
```kotlin
    mavenCentral {
        content {
            excludeModule("org.jetbrains.kotlinx", "kotlinx-coroutines-core-native")
            excludeModule("org.jetbrains.kotlinx", "atomicfu-native")
        }
    }
```
which seems to be invalid Gradle, at least in 5.x and 6.x. I *think* this works instead:
```kotlin
    mavenCentral().mavenContent {
        excludeModule("org.jetbrains.kotlinx", "kotlinx-coroutines-core-native")
        excludeModule("org.jetbrains.kotlinx", "atomicfu-native")
    }
```

The example uses an older version of Kotlin, 1.3.61, instead of 1.3.72, but I guess this is fine; I left it on 1.3.61.

The source sets seem not to work with IntelliJ; I'd expect after a refresh for src/main/kotlin to be marked as a module, but it's not.

When I perform a Gradle Sync, I get the following error:

```
Warning:<i><b>root project 'GodotKotlinTestGame': Unable to build Kotlin project configuration</b>
Details: org.gradle.api.internal.artifacts.ivyservice.DefaultLenientConfiguration$ArtifactResolveException: Could not resolve all files for configuration ':kotlinCompilerPluginClasspath'.
Caused by: org.gradle.internal.resolve.ModuleVersionResolveException: Could not resolve org.godotengine.kotlin:annotations-jvm:0.1.0-3.2.
Required by:
    project : > org.godotengine.kotlin:kotlin-compiler-plugin:0.1.0-3.2 > org.godotengine.kotlin:godot-annotation-processor:0.1.0-3.2
Caused by: org.gradle.internal.component.AmbiguousConfigurationSelectionException: Cannot choose between the following variants of org.godotengine.kotlin:annotations-jvm:0.1.0-3.2:
  - jvm-api
  - jvm-runtime
  - metadata-api
All of them match the consumer attributes:
  - Variant 'jvm-api' capability org.godotengine.kotlin:annotations-jvm:0.1.0-3.2:
      - Unmatched attributes:
          - Found org.gradle.libraryelements 'jar' but wasn't required.
          - Found org.gradle.status 'release' but wasn't required.
          - Found org.gradle.usage 'java-api' but wasn't required.
          - Found org.jetbrains.kotlin.platform.type 'jvm' but wasn't required.
  - Variant 'jvm-runtime' capability org.godotengine.kotlin:annotations-jvm:0.1.0-3.2:
      - Unmatched attributes:
          - Found org.gradle.libraryelements 'jar' but wasn't required.
          - Found org.gradle.status 'release' but wasn't required.
          - Found org.gradle.usage 'java-runtime' but wasn't required.
          - Found org.jetbrains.kotlin.platform.type 'jvm' but wasn't required.
  - Variant 'metadata-api' capability org.godotengine.kotlin:annotations-jvm:0.1.0-3.2:
      - Unmatched attributes:
          - Found org.gradle.status 'release' but wasn't required.
          - Found org.gradle.usage 'kotlin-api' but wasn't required.
          - Found org.jetbrains.kotlin.platform.type 'common' but wasn't required.</i>
```

Using Gradle 6.3 and IntelliJ 2019.3.4.

Thanks!

**Comment by piiertho** [comment]
Hi ! We're currently reworking the entire bindings, there was a lot of problems with former implementation. Release mechanism was one of those, which leads to `AmbiguousConfigurationSelectionException`.
We're doing this job in master-merge branch, but it is not ready yet.
For the exclude module, I take note, so that we can fix this behaviour in new implementation.
Thanks for catching up those problems !

**Comment by nanodeath** [comment]
Thanks @piiertho. Is there anything I can do to make things work, or should I just come back later?

**Comment by chippmann** [comment]
@nanodeath Yes but not without hassle. Personally i would just wait until we finished the rework as it shouldn't take that long anymore until we have a beta ready.
But if you really want to: You should be able to build the latest master branch. All you should have to do is checkout the project, init and update the submodules and execute `gradlew build` (optionally with your desired platform). It automatically should put the outputs into you mavenLocal.
It might be possible that you still get IDE dependency resolution errors after that (through commandline it should work then). Some users had this problem. Then you can write those here and I (hopefully) provide you with a fix. (We managed to fix the resolution issues for those users).
But note: if you want to try it out now, you are stuck with the gradle and kotlin version defined in master (i believe `1.3.61` and `6.0.1`) and your kotlin plugin for the IDE has to be at this version as well! Otherwise it will not work.
All of that said, I still think you probably should wait until we are ready for a beta with our current rework.

**Comment by nanodeath** [comment]
Works for me. While Kotlin is my favorite, C# is close enough and Godot's support for it is close enough that I have something to work with in the meantime.

Also keep up the good work. You're bringing my two favorite things together, Kotlin and gamedev 😄

**Comment by chippmann** [comment]
@nanodeath Ok for you to close this issue?
Btw: If you are interested in the progress, just frequently look into https://github.com/utopia-rise/godot-kotlin/tree/master-merge and the PR section :-)
