### ISSUE TITLE
Missing duplicate (with deep_copy bool) function for Dictionary

### ISSUE THREAD

**Issue by 2shady4u** [utopia-rise/godot-kotlin#39]
Hello!

**Duplicate(deep = false)**
I'm currently missing the duplicate function (with deep_copy functionalities) in the godot.core.Dictionary.

**keys and values?**
Also I'm not really sure about the implementation of keys and values as they currently seem
much too close to being actual fields in the Dictionary?
Like for example if I have following Dictionary dict:
```
{
"keys" : ["pear", "banana", "apple"],
"values": ["diamond", "pearl", "amethyst"]
}
```
I would expect dict.keys to give me a GDArray of ["pear", "banana", "apple"] instead of a GDArray of ["keys", "values"]? Currently this isn't the case and this might confuse adapters coming from GDScript. (I am aware that you can still use dict["keys"] and that will work... but the confusion can be avoided!)

**list\<String> and array\<String> to PoolStringArray**
There's a lot of other functionalities missing but having a conversion between list\<String> and PoolStringArray (as well as other lists<>/array<> to their respective Godot arrays) would be great to have.

**Comment by chippmann** [comment]
I implemented the missing duplicate function in the branch: https://github.com/utopia-rise/godot-kotlin/tree/feature/add_missing_functions_to_core_classes

Regarding Dictionary keys:
It already works like in GDScript as far as i can see.
In your example the keys of the Dictionary are in fact `keys` and `values`. And the values are `["pear", "banana", "apple"]` and `["diamond", "pearl", "amethyst"]`.
That works the same in GDScript?
What you basically ask for is a Map which does not exist in GDScript.
Or do i not understand you correctly?

Good idea about the list conversion. I look that i can implement that. Are there some other missing functionalities you want to see or missing functions you came across?

**Comment by 2shady4u** [comment]
I wanted to try this myself :'( I don't get why it doesn't work.

**Comment by chippmann** [comment]
> I wanted to try this myself :'( I don't get why it doesn't work.

Oh sorry ^^ Should i assign it to you?

**Comment by 2shady4u** [comment]
It's ok, I would just like to know the issue with my forked branch though. I would have made a PR days ago, if it just worked instead of crashed.

Will make an example to clarify the issue with keys and values.

**Comment by 2shady4u** [comment]
It's ok, I would just like to know the issue with my forked branch though. I would have made a PR days ago, if it just worked instead of crashed.

Will make an example to clarify the issue with keys and values.

**Comment by piiertho** [comment]
This is resolved by #47 no ?

**Comment by chippmann** [comment]
Only the duplicate function. The rest no. Maybe we should update the title then?
@2shady4u do you now want to add the missing functions or should one of us do this?

**Comment by 2shady4u** [comment]
Heyo,

I'm currently focusing on using the little time I have to finish the SQLite plugin so be free to add the missing functions whenever it suits you.

Regarding the dictionary: (some further explanation)

**GDScript code:**
```
var dict : Dictionary = {}
dict[values] = ["butter", "dragonfruit", "pineapple"]
dict[keys] = ["master", "bedroom", "closet"]

print(dict.values())
>> prints: [["butter", "dragonfruit", "pineapple"], ["master", "bedroom", "closet"]]
print(dict.values)
>> prints: ["butter", "dragonfruit", "pineapple"]

print(dict.keys())
>> prints: ["values", "keys"]
print(dict.keys)
>> prints: ["master", "bedroom", "closet"]
```

Godot Kotlin:
```
var dict : Dictionary = {}
dict[values] = ["butter", "dragonfruit", "pineapple"]
dict[keys] = ["master", "bedroom", "closet"]

GD.print(dict.values())
>> DOESNT EXIST
GD.print(dict.values)
>> prints: [["butter", "dragonfruit", "pineapple"], ["master", "bedroom", "closet"]]

GD.print(dict.keys())
>> DOESNT EXIST
GD.print(dict.keys)
>> prints: ["values", "keys"]
```

This difference is extremely confusing for beginning programmers in Godot-kotlin.
Does this makes sense to you? @chippmann

**Comment by piiertho** [comment]
I will answer on this. 
We are not in gdscript. I know being close from gdscript is an easy way to get in for new programmers. But this is kotlin, with functional syntaxes. We should not get out of kotlin's philosophy because gdscript is a language which lack of feature. So to me the keys and values have to be kept as backing fields.   
Edit: to clarify my point of view accessing using dict.keys would say accessing to a keys member, and that's not what we're doing in gdscript, we're accessing to an element in the dictionary (in the container), which is generally done in kotlin using get operator (ie dict[keys]).
Also according to the functional programming oriented way of thinking the duplicate() method can be moved to a duplicate backing field as it has no parameter.

**Comment by chippmann** [comment]
@piiertho Not for rhe duplicate function. It has a parameter which is a boolean.
Otherwise i think the same. But regardless of how i think about it, i wouldn't know how to implement that requested feature in a strongly typed language.
As far as i can see also the cpp bindings do not have such a feature.

@2shady4u please note here any other functions you want when you see them. I will now implement the list conversion functions and some GD singleton functions as global functions.
Feel free to just add others here as long as I'm working on it.
I will later edit your feature request to add the functions we will add so one does not have to search for them in the comments here.

**Comment by chippmann** [comment]
Changed the label from beta release to production release as the most important functions are added for the beta release.
The other functions are delivered in another beta version or the final release.

**Comment by chippmann** [comment]
Closing in favor of the merge. After the merge, there should be no functions missing, because the setup for the cinterop works differently.
I some functions are desperately needed until then, feel free to reopen it.
